# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This script builds the Docker image for the Data Validator.
# It can optionally build a specific version of the tool if the `_APP_VERSION`
# argument is provided.

FROM python:3.12.1

# App version is passed as a build argument.
# If not provided, the latest version will be installed.
ARG _APP_VERSION=""

# Set working directory
WORKDIR /app

# Copy and set up the entrypoint script
COPY samples/docker/entrypoint.sh .
RUN chmod +x entrypoint.sh

RUN apt-get update
RUN apt-get install -y build-essential gcc cmake
RUN apt-get install -y unixodbc-dev

RUN curl -sSL -O https://packages.microsoft.com/config/debian/$(grep VERSION_ID /etc/os-release | cut -d '"' -f 2 | cut -d '.' -f 1)/packages-microsoft-prod.deb
RUN dpkg -i packages-microsoft-prod.deb
RUN apt-get update

ENV ACCEPT_EULA=Y
RUN apt-get install -y msodbcsql18
RUN apt-get install -y mssql-tools18
ENV PATH="$PATH:/opt/mssql-tools18/bin"

# Install the Data Validator from PyPI
ENV PIPOPTS="--root-user-action=ignore"
RUN pip install ${PIPOPTS} --upgrade pip
RUN \
  if [ -z "$_APP_VERSION" ]; then \
    echo "Installing latest version of google-pso-data-validator"; \
    pip install ${PIPOPTS} google-pso-data-validator; \
  else \
    echo "Installing google-pso-data-validator version ${_APP_VERSION}"; \
    pip install ${PIPOPTS} google-pso-data-validator==${_APP_VERSION}; \
  fi
RUN pip install ${PIPOPTS} pyodbc

# The entrypoint script will handle connections and run the application
ENTRYPOINT ["./entrypoint.sh"]