# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This script builds the Docker image for the Data Validator.
# It can optionally build a specific version of the tool if the `_APP_VERSION`
# argument is provided.

FROM python:3.12.1-alpine

# App version is passed as a build argument.
# If not provided, the latest version will be installed.
ARG _APP_VERSION=""

# Set working directory
WORKDIR /app

# Copy and set up the entrypoint script
COPY samples/docker/entrypoint.sh .
RUN chmod +x entrypoint.sh

RUN apk update
RUN apk add curl build-base gcc cmake unixodbc-dev

# Install SQL Server ODBC driver.
# See https://learn.microsoft.com/en-us/sql/connect/odbc/linux-mac/installing-the-microsoft-odbc-driver-for-sql-server
ENV PKGDIR=/tmp
ENV architecture=amd64
RUN curl -O https://download.microsoft.com/download/9dcab408-e0d4-4571-a81a-5a0951e3445f/msodbcsql18_18.6.1.1-1_$architecture.apk -o /tmp/msodbcsql.apk
RUN curl -O https://download.microsoft.com/download/b60bb8b6-d398-4819-9950-2e30cf725fb0/mssql-tools18_18.6.1.1-1_$architecture.apk -o /tmp/mssql-tools.apk
# If the commands below fail please refer to the Microsoft instructions linked above for guidance.
RUN apk add --allow-untrusted /tmp/msodbcsql.apk /tmp/mssql-tools.apk

# Install the Data Validator from PyPI
ENV PIPOPTS="--root-user-action=ignore"
RUN pip install ${PIPOPTS} --upgrade pip
RUN \
  if [ -z "$_APP_VERSION" ]; then \
    echo "Installing latest version of google-pso-data-validator"; \
    pip install ${PIPOPTS} google-pso-data-validator; \
  else \
    echo "Installing google-pso-data-validator version ${_APP_VERSION}"; \
    pip install ${PIPOPTS} google-pso-data-validator==${_APP_VERSION}; \
  fi
RUN pip install ${PIPOPTS} pyodbc

# Entrypoint
ENTRYPOINT ["python","-m","data_validation"]